openshift:
  organization:
    name: "govaerts-jonas"
    state: "present"
  user:
    name: "openshift"
    state: "present"
    email: ""
  robots:
     - name: "pull"
       state: "present"
     - name: "push"
       state: "present"
  teams:
    - name: "read"
      role:  "member"
      state: "present"
      members:
      - name: "robot+pull"
        state: "present"
    - name: "write"
      state: "present"
      role: "creator"
      members:
      - name: "robot+push"
        state: "present"