openshift:
  organization:
    name: "openshift"
    state: "present"
  user:
    name: "openshift"
    state: "present"
  robots:
     - name: "pull"
       state: "present"
     - name: "push"
       state: "present"
  teams:
    - name: "read"
      role:  "member"
      state: "present"
      members:
      - "robot+pull"
    - name: "write"
      state: "present"
      role: "creator"
      members:
      - "robot+push"